Changed benchmark to compare with trivial aproach

diff --git a/benchmarking/run-benchmarking-bookstore b/benchmarking/run-benchmarking-bookstore
--- a/benchmarking/run-benchmarking-bookstore
+++ b/benchmarking/run-benchmarking-bookstore
@@ -1,12 +1,5 @@
 #!/bin/bash 
 
-# if [ ! "$#" == "5" ]
-# then
-#   echo "Usage ./extract_scaling.sh <max-n-cores> <crunch-sigma-percent> <lazy-unpack> <trigger-unpacking> <input-file>"
-#   echo "Example:  ./extract_scaling.sh 40 0.1 true true /path/to/lcio-file.slcio"
-#   exit 1
-# fi
-
 function printUsage() {
   echo "Usage:"
   echo "run-benchmarking-bookstore [options] --inputfile <slcio-file>"
@@ -14,16 +7,7 @@ function printUsage() {
   echo "Run MarlinMT for multi-core benchmarking"
   echo ""
   echo "Options:"
-  echo "  --mincores <int>           The start number of cores [default=2]"
-  echo "  --maxcores <int>           The end number of cores [default=2]"
-  echo "  --mincrunch <int>          The start crunch time (ms) [default=500]"
-  echo "  --maxcrunch <int>          The end crunch time (ms) [default=1000]"
-  echo "  --crunchstep <int>         The step in crunch time numbers [default=500]"
-  echo "  --sigmacrunch <float>      Introduce an event-by-event gaussian random"
-  echo "                             fluctuation in the crunch time [default=0]"
-  echo "  --inputfile <slcio-file>   The LCIO input file. Mandatory parameter !"
   echo "  --lazy                     Whether use option LazyUnpack for LCIO reading [default=false]"
-  echo "  --trigger                  Whether to trigger the event unpacking in worker threads [default=false]"
   echo "  -h --help                  Print help and exit"
   echo ""
 }
@@ -41,61 +25,34 @@ then
   exit 1
 fi
 
-OPTS=`getopt -o h -l mincores:,maxcores:,mincrunch:,maxcrunch:,crunchstep:,sigmacrunch:,inputfile:,histsigmapercent:,nbins:,nhistsmin:,nhistsmax:,nhistsstep:,nfillsmin:,nfillsmax:,nfillsstep:,memorylayout:,steeringfile:,accesstype:,lazy,trigger,native,help -n 'parse-options' -- "$@"`
+
+OPTS=`getopt -o h -l inputfile: -n 'parse-options' -- "$@"`
 eval set -- "$OPTS"
 
 # general configuration
-mincores=2
-maxcores=3
-lazyUnpack="false"
-triggerUnpacking="false"
-inputfile=""
-steeringfile=${MARLIN_DIR}/benchmarking/hist_filling.xml
+steeringfile="${MARLIN_DIR}benchmarking/hist_filling.xml"
+cores=(4 8 12)
+nhists=(1 2 3)
+nfills=(1 10 100)
+nbins=(500 1000 1500)
+accesstypes=("Rotating" "Continuous")
+memorylayouts=("Share" "Copy" "Mutex")
 
-# cpu_crunch configuration
-mincrunch=50
-maxcrunch=100
-crunchstep=50
-sigmapercent=0
-
-# histogram processor configuration
-nbins=1000
-nhistsmin=20
-nhistsmax=2020
-nhistsstep=500
-nfillsmin=100000
-nfillsmax=300000
-nfillsstep=100000
-memorylayout="Copy"
-native="false"
-accesstype="0"
-	
+accesstype_to_id () {
+	if [[ $1 == "Rotating" ]]; then
+		echo 0
+	elif [[ $1 == "Continuous" ]]; then
+		echo 1
+	else
+		>&2 echo "unrecognized access type: '$type'"
+		exit 1
+	fi
+}
 
 while true; do
   case "$1" in
-	# general configuration
-    --mincores ) mincores=$2; shift; shift ;;
-    --maxcores ) maxcores=$2; shift; shift ;;
     --inputfile ) inputfile=$2; shift; shift ;;
-    --lazy ) lazyUnpack="true"; shift ;;
-    --trigger ) triggerUnpacking="true"; shift ;;
-		--steeringfile ) steeringfile=$2; shift; shift;;
-	# cpu crunch configuration
-    --mincrunch ) mincrunch=$2; shift; shift ;;
-    --maxcrunch ) maxcrunch=$2; shift; shift ;;
-    --crunchstep ) crunchstep=$2; shift; shift ;;
-    --sigmacrunch ) sigmacrunch=$2; shift; shift ;;
-	# histogram processor configuration
-		--nbins ) nbins=$2; shift; shift ;;
-		--nhistsmin ) nhistsmin=$2; shift; shift ;;
-		--nhistsmax ) nhistsmax=$2; shift; shift ;;
-		--nhistsstep ) nhistsstep=$2; shift; shift ;;
-		--nfillsmin ) nfillsmin=$2; shift; shift ;;
-		--nfillsmax ) nfillsmax=$2; shift; shift ;;
-		--nfillsstep ) nfillsstep=$2; shift; shift ;;
-		--memorylayout ) memorylayout=$2; shift; shift ;;
-		--native ) native="true"; shift ;;
-		--accesstype ) accesstype=$2; shift; shift ;;
+    --lazy ) lazyunpack="true"; shift ;;
 	# other inputs
     -h | --help )  printUsage; exit 0 ;;
     -- ) shift; break ;;
@@ -111,55 +68,9 @@ then
   exit 1
 fi
 
-cores=`seq ${mincores} ${maxcores} | tr '\n' ' '`
-if [ $crunchstep -eq 0 ]; then crunchtimes=(${mincrunch}); else
-	crunchtimes=`seq ${mincrunch} ${crunchstep} ${maxcrunch} | tr '\n' ' '`
-fi
-if [ $nhistsstep -eq 0 ]; then nhists=(${nhistsmin}); else
-	nhists=`seq ${nhistsmin} ${nhistsstep} ${nhistsmax} | tr '\n' ' '`
-fi
-if [ $nfillsstep -eq 0 ]; then nfills=(${nfillsmin}); else
-	nfills=`seq ${nfillsmin} ${nfillsstep} ${nfillsmax} | tr '\n' ' '`
-fi
 
-lazyUnpackStr=""
-triggerUnpackingStr=""
+output="MarlinMTBenchmarking.csv"
 
-if [ "${lazyUnpack}" == "true" ]
-then
-  lazyUnpackStr="lazy"
-else
-  lazyUnpackStr="nolazy"
-fi
-
-if [ "${triggerUnpacking}" == "true" ]
-then
-  triggerUnpackingStr="trig"
-else
-  triggerUnpackingStr="notrig"
-fi
-
-output="MarlinMTBenchmarking_Lazy.${lazyUnpackStr}_Trigger.${triggerUnpackingStr}_Sigma.${sigmapercent}_MemoryLayout.${memorylayout}_Native.${native}_AccessType.${accesstype}_nBins.${nbins}.txt"
-
-if [ -f ${output} ]
-then
-  rm ${output}
-fi
-
-echo "Running with following settings:"
-echo "  - n cores: ${cores}"
-echo "  - crunch times: ${crunchtimes}"
-echo "  - crunch sigma percentage: $sigmapercent"
-echo "  - lazy unpacking ? $lazyUnpack"
-echo "  - trigger unpacking ? $triggerUnpacking"
-echo "  - LCIO input file: $inputfile"
-echo "  - Marlin steering file: $steeringfile"
-echo "  - Benchmark output file: $output"
-echo "  - nfills: ${nfills}"
-
-# load the file in the cache for next
-echo "Loading input file into cache: ${inputfile}"
-anajob ${inputfile} >> /dev/null
 
 if [[ "$native" == "true" ]] && [[ $memorylayout != "Shared" ]]; then
 	echo "ERROR copied memory layout is native not possible!"
@@ -168,74 +79,83 @@ fi
 
 echo "Start benchmarking ..."
 
-echo "concurrency,crunchTime,crunchSigma,nHists,nFills,nBins,\
-tReal,tUser,tSys,tSerial,tParallel,scaling" > ${output}
+echo "$c,$nf,$at,$ml,$nh,$nb,$serial,$parallel,$scaling,$real,$unpack,$fill"
+echo "concurrency,nFills,accessType,mutex,memoryLayout,nHists,nBins,tSerial,tParallel,scaling,tReal,tUnpack,tFill" > $output
 
-for c in ${cores}
-do
-	for nf in ${nfills}
-	do
-		for cr in ${crunchtimes}
-		do
-			crunchSigma=`echo "(${cr}*${sigmapercent})" | bc`
-			for nh  in ${nhists}
-			do
-				echo "Running MarlinMT with:"
-				echo "  general:"
-				echo "  -- N cores:            ${c}"
-				echo "  -- Lazy unpacking:     ${lazyUnpack}"
-				echo "  -- Trigger unpacking:  ${triggerUnpacking}"
-				echo "  cpu_crunch:"
-				echo "  -- Crunch time:        ${cr}"
-				echo "  -- Crunch sigma:       ${crunchSigma}"
-				echo "  histogram filling:"
-				echo "  -- memory layout: 	   ${memorylayout}"
-				echo "  -- access type:        ${accesstype}"
-				echo "  -- number histograms:  ${nh}"
-				echo "  -- number bins:        ${nbins}"
-				echo "  -- number fills:       ${nf}"
-				totalTime=(`time (MarlinMT \
-				${steeringfile} \
-				--constant.TriggerUnpacking="${triggerUnpacking}" \
-				--constant.AccesType="${accesstype}" \
-				--datasource.LCIOInputFiles="${inputfile}" \
-				--datasource.LazyUnpack="${lazyUnpack}" \
-				--CPUCrunch.CrunchTime=${cr} \
-				--CPUCrunch.CrunchSigma=${crunchSigma} \
-				--bookstore.DefaultMemoryLayout=${memorylayout} \
-				--HistFilling0.NBins=${nbins} \
-				--HistFilling0.NHists=${nh} \
-				--HistFilling0.NFills=${nf} \
-				--HistFilling1.NBins=${nbins} \
-				--HistFilling1.NHists=${nh} \
-				--HistFilling1.NFills=${nf} \
-				--HistFillingNative.NBins=${nbins} \
-				--HistFillingNative.NHists=${nh} \
-				--HistFillingNative.NFills=${nf} \
-				--constant.RunNative=${native} \
-				--global.Concurrency=${c} > scaling_temp_$$.log ) 2>&1 1>/dev/null `)
-				if [ $? -ne 0 ]; then
-					echo "MarlinMT failed!, stop benchmarks!"
-					exit 1
+
+echo "Running with following settings:"
+echo "  - n cores:      ${cores[@]}"
+echo "  - n fills:      ${nfills[@]}"
+echo "  - n Hists:      10^(${nhists[@]})"
+echo "  - n bins:       ${nbins[@]}"
+echo "  - access types: ${accesstypes[@]}"
+echo "  - layout:       ${memorylayouts[@]}"
+echo "  - Marlin steering file: $steeringfile"
+echo "  - Benchmark output file: $output"
+
+# load the file in the cache for next
+echo "Loading input file into cache: ${inputfile}"
+# anajob ${inputfile} >> /dev/null
+
+for c in ${cores[@]}; do
+	for nf in ${nfills[@]}; do
+		for at in ${accesstypes[@]}; do
+			atid=`accesstype_to_id $at`
+			for ml in ${memorylayouts[@]}; do
+				if [[ $ml = "Mutex" ]]; then
+					ml="Share"
+					mutex="true"
+				else 
+					mutex="false"
 				fi
-				serial=$( cat scaling_temp_$$.log | grep serial | awk '{print $7}' )
-				parallel=$( cat scaling_temp_$$.log |  grep serial | awk '{print $9}' )
-				scaling=$( cat scaling_temp_$$.log | grep serial| awk '{print $11}' )
-				real=${totalTime[1]}
-				user=${totalTime[3]}
-				sys=${totalTime[5]}
-				echo "Result: "
-				echo "  serial Time:   ${serial}"
-				echo "  parallel Time: ${parallel}"
-				echo "  scaling:       ${scaling}"
-				echo "  total Time:    ${real}"
-				echo "${c},\
-${cr},${crunchSigma},\
-${nh},${nf},${nbins},\
-${real},${user},${sys},\
-${serial},${parallel},${scaling}" >> ${output}
-				echo ""
+				for nh in ${nhists[@]}; do
+					for nb in ${nbins[@]}; do
+						echo "Running MarlinMT with:"
+						echo "  general:"
+						echo "  -- N cores:            ${c}"
+						echo "  histogram filling:"
+						echo "  -- use mutex:          ${mutex}"
+						echo "  -- memory layout:      ${ml}"
+						echo "  -- access type:        ${at}"
+						echo "  -- number histograms:  ${nh}"
+						echo "  -- number bins:        ${nb}"
+						echo "  -- number fills:       ${nf}"
+						totalTime=(`time ( MarlinMT \
+							${steeringfile} \
+							--HistFilling.NBins="$nb" \
+							--HistFilling.NHists10="$nh" \
+							--HistFilling.NFills="$nf" \
+							--HistFilling.AccessType="$atid" \
+							--HistFilling.UseMutex="$mutex" \
+							--datasource.LCIOInputFiles="$inputfile" \
+							--datasource.LazyUnpack="true" \
+							--bookstore.DefaultMemoryLayout=${ml} \
+							--global.Concurrency=${c} > scaling_temp_.log ) 2>&1 1>/dev/null `)
+						if [ $? -ne 0 ]; then
+							>&2 echo "MarlinMT failed!, stop benchmarks!"
+							exit 1
+						fi
+						totalProcessorTime=(`cat scaling_temp_.log | grep serial | awk '{print $7, $9, $11}'`)
+						serial=${totalProcessorTime[0]}
+						parallel=${totalProcessorTime[1]}
+						scaling=${totalProcessorTime[2]}
+						real=${totalTime[1]}
+						unpackTime=`cat scaling_temp_.log \
+							| sed -n '/EventUnpacking.*==>/s/.*EventUnpacking\s*\(\S*\).*/\1/p'`
+						fillTime=`cat scaling_temp_.log \
+							| sed -n '/HistFilling.*==>/s/.*HistFilling\s*\(\S*\).*/\1/p'`
+						echo "Result:"
+						echo "  serial Time:   $serial"
+						echo "  parallel Time: $parallel"
+						echo "  scaling:       $scaling"
+						echo "  real Time:     $real"
+						echo "  fill Time:     $fillTime"
+						echo "  unpackTime:    $unpackTime"
+						echo "$c,$nf,$at,$mutex,$ml,$nh,$nb,$serial,$parallel,$scaling,$real,$unpackTime,$fillTime" >> $output
+					done
+				done
 			done
 		done
 	done
 done
+
