Added native processor and expand benchmark
* MarlinBenchBookNativeProcessor same as MarlinBenchBookProcessor but
  implemented with root directly for performance compares

* add options to use it in run-benchmarks-bookstore
* rename run-benchmarks to run-benchmarsk-scheduler

diff --git a/benchmarking/run-benchmarking-bookstore b/benchmarking/run-benchmarking-bookstore
--- a/benchmarking/run-benchmarking-bookstore
+++ b/benchmarking/run-benchmarking-bookstore
@@ -1,6 +1,5 @@
 #!/bin/bash
 
-
 # if [ ! "$#" == "5" ]
 # then
 #   echo "Usage ./extract_scaling.sh <max-n-cores> <crunch-sigma-percent> <lazy-unpack> <trigger-unpacking> <input-file>"
@@ -42,7 +41,7 @@ then
   exit 1
 fi
 
-OPTS=`getopt -o h -l mincores:,maxcores:,mincrunch:,maxcrunch:,crunchstep:,sigmacrunch:,inputfile:,histsigmapercent:,nbins:,nhistsmin:,nhistsmax:,nhistsstep:,nfills:,memorylayout:,steeringfile:,lazy,trigger,help -n 'parse-options' -- "$@"`
+OPTS=`getopt -o h -l mincores:,maxcores:,mincrunch:,maxcrunch:,crunchstep:,sigmacrunch:,inputfile:,histsigmapercent:,nbins:,nhistsmin:,nhistsmax:,nhistsstep:,nfills:,memorylayout:,steeringfile:,lazy,trigger,native,help -n 'parse-options' -- "$@"`
 eval set -- "$OPTS"
 
 # general configuration
@@ -51,7 +50,7 @@ maxcores=2
 lazyUnpack="false"
 triggerUnpacking="false"
 inputfile=""
-steeringfile=${MARLIN_DIR}/benchmarking/cpu_crunching.xml
+steeringfile=${MARLIN_DIR}/benchmarking/hist_filling.xml
 
 # cpu_crunch configuration
 mincrunch=500
@@ -66,6 +65,7 @@ nhistsmax=40
 nhistsstep=5
 nfills=1000
 memorylayout="Copy"
+native="false"
 	
 
 while true; do
@@ -89,6 +89,7 @@ while true; do
 		--nhistsstep ) nhistsstep=$2; shift; shift ;;
 		--nfills ) nfills=$2; shift; shift ;;
 		--memorylayout ) memorylayout=$2; shift; shift ;;
+		--native ) native="true"; shift ;;
 	# other inputs
     -h | --help )  printUsage; exit 0 ;;
     -- ) shift; break ;;
@@ -146,13 +147,19 @@ echo "  - Benchmark output file: $output"
 echo "Loading input file into cache: ${inputfile}"
 anajob ${inputfile} >> /dev/null
 
+if [[ "$native" == "true" ]] && [[ $memorylayout != "Shared" ]]; then
+	echo "ERROR copied memory layout is native not possible!"
+	exit 1
+fi
+echo "$memorylayout native: $nativeShared REMOVE! TODO"
+
 echo "Start benchmarking ..."
 for c in ${cores}
 do
   for cr in ${crunchtimes}
   do
 		crunchSigma=`echo "(${cr}*${sigmapercent})" | bc`
-		for nhists in ${nhists}
+		for nh  in ${nhists}
 		do
 			echo "Running MarlinMT with:"
 			echo "  general:"
@@ -163,7 +170,7 @@ do
 			echo "  -- Crunch time:        ${cr}"
 			echo "  -- Crunch sigma:       ${crunchSigma}"
 			echo "  histogram filling:"
-			echo "  -- number histograms:  ${nhists}"
+			echo "  -- number histograms:  ${nh}"
 			echo "  -- number bins:        ${nbins}"
 			echo "  -- number fills:       ${nfills}"
 			MarlinMT \
@@ -173,10 +180,19 @@ do
 			--datasource.LazyUnpack="${lazyUnpack}" \
 			--CPUCrunch.CrunchTime=${cr} \
 			--CPUCrunch.CrunchSigma=${crunchSigma} \
+			--bookstore.DefaultMemoryLayout=${memorylayout} \
 			--HistFilling.NBins=${nbins} \
-			--HistFilling.NHists=${nhists} \
+			--HistFilling.NHists=${nh} \
 			--HistFilling.NFills=${nfills} \
+			--HistFillingNative.NBins=${nbins} \
+			--HistFillingNative.NHists=${nh} \
+			--HistFillingNative.NFills=${nfills} \
+			--constant.RunNative=${native} \
 			--global.Concurrency=${c} > scaling_temp_$$.log 
+			if [ $? -ne 0 ]; then
+				echo "MarlinMT failed!, stop benchmarks!"
+				exit 1
+			fi
 			serial=$( cat scaling_temp_$$.log | grep serial | awk '{print $7}' )
 			parallel=$( cat scaling_temp_$$.log |  grep serial | awk '{print $9}' )
 			scaling=$( cat scaling_temp_$$.log | grep serial| awk '{print $11}' )
@@ -184,7 +200,7 @@ do
 			echo "  serial Time:   ${serial}"
 			echo "  parallel Time: ${parallel}"
 			echo "  scaling:       ${scaling}"
-			echo "${c} ${cr} ${crunchSigma} ${serial} ${parallel} ${scaling}" >> ${output}
+			echo "${c} ${cr} ${crunchSigma} ${nh} ${serial} ${parallel} ${scaling}" >> ${output}
 			echo ""
 		done
   done
